{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.appName }}-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: roboshop-secret-manager
    kind: ClusterSecretStore
  target:
    name: {{ .Values.appName }}
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: {{ .Values.appName }}
{{- end }}
