{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "roboshop.fullname" . }}
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{ .Values.ingress.dnsName }}
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ include "roboshop.fullname" . }}
            servicePort: {{ .Values.appPort }}
{{- end }}
