{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "roboshop.fullname" . }}
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{ .Values.ingress.dnsName }}
    http:
      paths:
        - path: /
          backend:
            service:
              name: service1
              port:
                number: 80
{{- end }}
